### PR TITLE
add traditional chinese tw manually

### PR DESCRIPTION
**Pull request by leayingly**
Is it possible to also add zh-TW? It's more frequently used than zh-HANS IMHO, and I took the liberty to add this. 

Thank you, please review and let me know! :)

### CODE REVIEW

**Comment by cupcakearmy** [comment]
Thanks!

**Comment by leayingly** [comment]
May I also understand how version can be bumped up and released? Would love to test it for my case! Thank you! 🍺

**Comment by cupcakearmy** [comment]
Sure, have a look at https://github.com/locale-switcher/locale-switcher/blob/main/RELEASE.md
There it should tell you how tu bump & built.

**Comment by cupcakearmy** [comment]
I've uploaded to the stores, will be online in a few hours probably

**Comment by leayingly** [comment]
Thank you, works like a charm!

**Pull request merged**
