### PR TITLE
Use json stringify.

### PR DESCRIPTION
**Pull request by m1k1o**
Current implementation could be vulnerable to command injection.

### CODE REVIEW

**Comment by cupcakearmy** [comment]
Hey :) Thanks for submitting this.
Could you provide more explaination / examples?

I thing you mean since we are templating javascript directly. The possible values though are coming form the extension itself.
Now following along then we would need to escape `locale[0]` too then, as that would still be "unescaped"
However i'm not sure this is actually a sec vuln. 

Now a valid point would be:
1. locales might be loaded from session storage (`LOCALE_SWITCHER_LANGUAGE`)
2. Bad actor modifies session storage on it's own website
3. bad code is executed on the host/domain of a bad actor -> is it really a compromise?

The actual solution would not be to JSON encode, but rather check validity of input with a regexp I'd suggest.
Probably the best point would be here:
https://github.com/locale-switcher/locale-switcher/blob/e24d502482f7070cf247320e4b8295f8ebbe1d53/src/shared/utils.ts#L4-L7

and check if they conform to a locale format with regexp and throw an error if not. Exmaple: https://regex101.com/r/RKA2IL/1

Something like this: `/([A-Za-z\d]+)(-[A-Za-z\d])*/` only letters and digits allowed

**Comment by cupcakearmy** [comment]
A proposal would be #45 

Thoughts?

**Comment by m1k1o** [comment]
Thats also fine. But `JSON.stringify` works as generic safe method to pass arguments to any JS function without additional custom logic.

**Comment by cupcakearmy** [comment]
Thanks again for bringing it up, and to add validation at an important step!

**Pull request closed without merging**
