### PR TITLE
script to download locales, support for native search

### LINKED ISSUE #9: es-419 for Latin American Spanish
Would you consider adding the `es-419` locale for Latin American Spanish. It would be really helpful for testing when we don't distinguish between different locales in the America's but we do have a difference with `es-ES`

### LINKED ISSUE #15: kurdish language is missing
there isn't any option for Kurdish language 'ku'

### PR DESCRIPTION
**Pull request by cupcakearmy**
Download locaes from https://www.localeplanet.com/icu/index.html which has a more complete list.

- fixes #9 
- fixes #15

### CODE REVIEW

**Comment by athyuttamre** [comment]
Interesting resource! I did a bit more research, and it looks like HTTP and HTML use the IETF Language Tag standard [0]. The canonical list of these tags comes from the IANA, and is hosted here: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry.

I wonder if we should perhaps directly parse that website instead, and filter down to the ones that are `Type: language` or `Type: redundant`? Happy to approve this as-is too, but we might as well go to the canonical source. 

[0] https://en.wikipedia.org/wiki/IETF_language_tag

**Comment by cupcakearmy** [comment]
> Interesting resource! I did a bit more research, and it looks like HTTP and HTML use the IETF Language Tag standard [0]. The canonical list of these tags comes from the IANA, and is hosted here: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry.
> 
> I wonder if we should perhaps directly parse that website instead, and filter down to the ones that are `Type: language` or `Type: redundant`? Happy to approve this as-is too, but we might as well go to the canonical source.
> 
> [0] https://en.wikipedia.org/wiki/IETF_language_tag

Yeah saw that too. Probably the best idea to get the canonical :)

**Comment by cupcakearmy** [comment]
I now remember why I did not parse the original:

There is a bit of logic involved, so the standard is actually more than one document https://en.wikipedia.org/wiki/ISO_639 so we would need to combine them. The list from the url you posted unfortunately does not contain everything we would need.

**Comment by athyuttamre** [comment]
Hmm is there any specific language that's missing on that URL? I think the IANA list just keeps the latest version of all the locales. I see that both `es-419` and `ku` are also included.

**Comment by cupcakearmy** [comment]
> Hmm is there any specific language that's missing on that URL? I think the IANA list just keeps the latest version of all the locales. I see that both `es-419` and `ku` are also included.

For example the german in luxembourg `de_LU` is not in it or italian in san marino `it_SM` as far as I can tell

**Pull request merged**
